name: release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_IO_TOKEN }}
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --dry-run
  release:
    strategy:
      matrix:
        name: [linux, macos, windows]
        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/rust-gh-actions-test
            asset_name: rust-gh-actions-test-linux
          - name: macos
            os: macos-latest
            artifact_name: target/release/rust-gh-actions-test
            asset_name: rust-gh-actions-test-macos
          - name: windows
            os: windows-latest
            artifact_name: target/release/rust-gh-actions-test.exe
            asset_name: rust-gh-actions-test-windows.exe
    runs-on: ${{ matrix.os }}
    name: release-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - run: cp ${{ matrix.artifact_name }} ${{ matrix.asset_name }}
        shell: bash
      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
